### ISSUE TITLE
POST /push/subscribe

### ISSUE THREAD

**Issue by tzanko-matev** [santiment/santiment-backend#13]
{
userId: string,
iosToken: string
OR
androidGCMId: string
}

Returns:

200 OK

or

{
error:string
}

**Comment by igormatyushkin014** [comment]
@tzanko-matev  Let's change JSON structure.

----

Request:

```
{
    "ios": {
        "token": "abcdefgh"
    }
    
    "android": {
        "token": "abcdefgh"
    }
}
```

----

Response:

```
{
    "device": {
        "uid": "abc123def456qwe"
    }
    
    "error": {
       "description": "here should be some description"
    }
}
```

----

When endpoint receives the token, it should generate new device UID and store it in server-side database. If the token was already sent before, just return associated device UID without creating new UID.

Also, you need to put device OS into server-side storage so we could get more detailed statistics in the future.
